version: "3.3"

services:
    webserver:
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        container_name: laravel_nginx
        volumes:
            - ./:/var/www/html
            - .docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/data/logs/nginx:/var/log/nginx
        ports:
            - 8080:80
        depends_on:
            - mysql
            - php-fpm
        networks:
            - app-network

    php-fpm:
        build:
            context: .
            dockerfile: .docker/php-fpm/Dockerfile
        container_name: laravel_php-fpm
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    mysql:
        image: mysql
        container_name: laravel_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: techwiz3
            MYSQL_ROOT_PASSWORD: techwiz3
        networks:
            - app-network

    workspace:
        build:
            context: .
            dockerfile: .docker/workspace/Dockerfile
        container_name: laravel_workspace
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        tty: true
        networks:
            - app-network

    #Docker Networks
networks:
    app-network:
        driver: bridge
