version: "3.3"

services:
    mysqldb:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: techwiz3
            MYSQL_DATABASE: techwiz3
